"""Reference card-pool order from the decompiled STS2 models."""

from __future__ import annotations

from enum import Enum

from sts2_env.core.enums import CardId


class CardPoolId(Enum):
    IRONCLAD = "Ironclad"
    SILENT = "Silent"
    DEFECT = "Defect"
    REGENT = "Regent"
    NECROBINDER = "Necrobinder"
    COLORLESS = "Colorless"
    CURSE = "Curse"
    DEPRECATED = "Deprecated"
    EVENT = "Event"
    QUEST = "Quest"
    STATUS = "Status"
    TOKEN = "Token"


COLORLESS_CARD_POOL: tuple[CardId, ...] = (
    CardId.ALCHEMIZE,
    CardId.ANOINTED,
    CardId.AUTOMATION,
    CardId.BEACON_OF_HOPE,
    CardId.BEAT_DOWN,
    CardId.BELIEVE_IN_YOU,
    CardId.BOLAS,
    CardId.CALAMITY_CARD,
    CardId.CATASTROPHE,
    CardId.COORDINATE_CARD,
    CardId.DARK_SHACKLES,
    CardId.DISCOVERY,
    CardId.DRAMATIC_ENTRANCE,
    CardId.ENTROPY,
    CardId.EQUILIBRIUM,
    CardId.ETERNAL_ARMOR,
    CardId.FASTEN,
    CardId.FINESSE,
    CardId.FISTICUFFS,
    CardId.FLASH_OF_STEEL,
    CardId.GANG_UP,
    CardId.GOLD_AXE,
    CardId.HAND_OF_GREED,
    CardId.HIDDEN_GEM,
    CardId.HUDDLE_UP,
    CardId.IMPATIENCE,
    CardId.INTERCEPT_CARD,
    CardId.JACK_OF_ALL_TRADES,
    CardId.JACKPOT,
    CardId.KNOCKDOWN,
    CardId.LIFT,
    CardId.MASTER_OF_STRATEGY,
    CardId.MAYHEM_CARD,
    CardId.MIMIC,
    CardId.MIND_BLAST,
    CardId.NOSTALGIA_CARD,
    CardId.OMNISLICE,
    CardId.PANACHE_CARD,
    CardId.PANIC_BUTTON,
    CardId.PREP_TIME,
    CardId.PRODUCTION,
    CardId.PROLONG,
    CardId.PROWESS,
    CardId.PURITY,
    CardId.RALLY,
    CardId.REND,
    CardId.RESTLESSNESS,
    CardId.ROLLING_BOULDER,
    CardId.SALVO,
    CardId.SCRAWL,
    CardId.SECRET_TECHNIQUE,
    CardId.SECRET_WEAPON,
    CardId.SEEKER_STRIKE,
    CardId.SHOCKWAVE,
    CardId.SPLASH,
    CardId.STRATAGEM,
    CardId.TAG_TEAM,
    CardId.THE_BOMB_CARD,
    CardId.THE_GAMBIT,
    CardId.THINKING_AHEAD,
    CardId.THRUMMING_HATCHET,
    CardId.ULTIMATE_DEFEND,
    CardId.ULTIMATE_STRIKE,
    CardId.VOLLEY,
)

CURSE_CARD_POOL: tuple[CardId, ...] = (
    CardId.ASCENDERS_BANE,
    CardId.BAD_LUCK,
    CardId.CLUMSY,
    CardId.CURSE_OF_THE_BELL,
    CardId.DEBT,
    CardId.DECAY,
    CardId.DOUBT,
    CardId.ENTHRALLED,
    CardId.FOLLY,
    CardId.GREED,
    CardId.GUILTY,
    CardId.INJURY,
    CardId.NORMALITY,
    CardId.POOR_SLEEP,
    CardId.REGRET,
    CardId.SHAME,
    CardId.SPORE_MIND,
    CardId.WRITHE,
)

DEFECT_CARD_POOL: tuple[CardId, ...] = (
    CardId.ADAPTIVE_STRIKE,
    CardId.ALL_FOR_ONE,
    CardId.BALL_LIGHTNING,
    CardId.BARRAGE,
    CardId.BEAM_CELL,
    CardId.BIASED_COGNITION_CARD,
    CardId.BOOST_AWAY,
    CardId.BOOT_SEQUENCE,
    CardId.BUFFER_CARD,
    CardId.BULK_UP,
    CardId.CAPACITOR,
    CardId.CHAOS,
    CardId.CHARGE_BATTERY,
    CardId.CHILL,
    CardId.CLAW,
    CardId.COLD_SNAP,
    CardId.COMPACT,
    CardId.COMPILE_DRIVER,
    CardId.CONSUMING_SHADOW,
    CardId.COOLANT,
    CardId.COOLHEADED,
    CardId.CREATIVE_AI_CARD,
    CardId.DARKNESS_CARD,
    CardId.DEFEND_DEFECT,
    CardId.DEFRAGMENT,
    CardId.DOUBLE_ENERGY,
    CardId.DUALCAST,
    CardId.ECHO_FORM_CARD,
    CardId.ENERGY_SURGE,
    CardId.FERAL,
    CardId.FIGHT_THROUGH,
    CardId.FLAK_CANNON,
    CardId.FOCUSED_STRIKE_CARD,
    CardId.FTL,
    CardId.FUSION,
    CardId.GENETIC_ALGORITHM,
    CardId.GLACIER,
    CardId.GLASSWORK,
    CardId.GO_FOR_THE_EYES,
    CardId.GUNK_UP,
    CardId.HAILSTORM,
    CardId.HELIX_DRILL,
    CardId.HOLOGRAM,
    CardId.HOTFIX,
    CardId.HYPERBEAM,
    CardId.ICE_LANCE,
    CardId.IGNITION,
    CardId.ITERATION_CARD,
    CardId.LEAP,
    CardId.LIGHTNING_ROD,
    CardId.LOOP_CARD,
    CardId.MACHINE_LEARNING_CARD,
    CardId.METEOR_STRIKE,
    CardId.MODDED,
    CardId.MOMENTUM_STRIKE,
    CardId.MULTI_CAST,
    CardId.NULL_CARD,
    CardId.OVERCLOCK,
    CardId.QUADCAST,
    CardId.RAINBOW,
    CardId.REBOOT,
    CardId.REFRACT,
    CardId.ROCKET_PUNCH,
    CardId.SCAVENGE,
    CardId.SCRAPE,
    CardId.SHADOW_SHIELD,
    CardId.SHATTER,
    CardId.SIGNAL_BOOST,
    CardId.SKIM,
    CardId.SMOKESTACK,
    CardId.SPINNER_CARD,
    CardId.STORM_CARD,
    CardId.STRIKE_DEFECT,
    CardId.SUBROUTINE,
    CardId.SUNDER,
    CardId.SUPERCRITICAL,
    CardId.SWEEPING_BEAM,
    CardId.SYNCHRONIZE,
    CardId.SYNTHESIS,
    CardId.TEMPEST,
    CardId.TESLA_COIL,
    CardId.THUNDER_CARD,
    CardId.TRASH_TO_TREASURE,
    CardId.TURBO,
    CardId.UPROAR,
    CardId.VOLTAIC,
    CardId.WHITE_NOISE,
    CardId.ZAP,
)

DEPRECATED_CARD_POOL: tuple[CardId, ...] = (
    CardId.DEPRECATED_CARD,
)

EVENT_CARD_POOL: tuple[CardId, ...] = (
    CardId.APOTHEOSIS,
    CardId.APPARITION,
    CardId.BRIGHTEST_FLAME,
    CardId.BYRD_SWOOP,
    CardId.CALTROPS,
    CardId.CLASH,
    CardId.DISTRACTION,
    CardId.DUAL_WIELD,
    CardId.ENLIGHTENMENT,
    CardId.ENTRENCH,
    CardId.EXTERMINATE,
    CardId.FEEDING_FRENZY_CARD,
    CardId.HELLO_WORLD_CARD,
    CardId.MAD_SCIENCE,
    CardId.MAUL,
    CardId.METAMORPHOSIS,
    CardId.NEOWS_FURY,
    CardId.OUTMANEUVER,
    CardId.PECK,
    CardId.REBOUND,
    CardId.RELAX,
    CardId.RIP_AND_TEAR,
    CardId.SQUASH,
    CardId.STACK,
    CardId.TORIC_TOUGHNESS,
    CardId.WISH,
    CardId.WHISTLE,
)

IRONCLAD_CARD_POOL: tuple[CardId, ...] = (
    CardId.AGGRESSION_CARD,
    CardId.ANGER,
    CardId.ARMAMENTS,
    CardId.ASHEN_STRIKE,
    CardId.BARRICADE_CARD,
    CardId.BASH,
    CardId.BATTLE_TRANCE,
    CardId.BLOOD_WALL,
    CardId.BLOODLETTING,
    CardId.BLUDGEON,
    CardId.BODY_SLAM,
    CardId.BRAND,
    CardId.BREAK,
    CardId.BREAKTHROUGH,
    CardId.BULLY,
    CardId.BURNING_PACT,
    CardId.CASCADE,
    CardId.CINDER,
    CardId.COLOSSUS_CARD,
    CardId.CONFLAGRATION,
    CardId.CORRUPTION_CARD,
    CardId.CRIMSON_MANTLE,
    CardId.CRUELTY_CARD,
    CardId.DARK_EMBRACE_CARD,
    CardId.DEFEND_IRONCLAD,
    CardId.DEMON_FORM_CARD,
    CardId.DEMONIC_SHIELD,
    CardId.DISMANTLE,
    CardId.DOMINATE,
    CardId.DRUM_OF_BATTLE_CARD,
    CardId.EVIL_EYE,
    CardId.EXPECT_A_FIGHT,
    CardId.FEED,
    CardId.FEEL_NO_PAIN_CARD,
    CardId.FIEND_FIRE,
    CardId.FIGHT_ME,
    CardId.FLAME_BARRIER_CARD,
    CardId.FORGOTTEN_RITUAL,
    CardId.GRAPPLE,
    CardId.HAVOC,
    CardId.HEADBUTT,
    CardId.HELLRAISER_CARD,
    CardId.HEMOKINESIS,
    CardId.HOWL_FROM_BEYOND,
    CardId.IMPERVIOUS,
    CardId.INFERNAL_BLADE,
    CardId.INFERNO_CARD,
    CardId.INFLAME,
    CardId.IRON_WAVE,
    CardId.JUGGERNAUT_CARD,
    CardId.JUGGLING_CARD,
    CardId.MANGLE,
    CardId.MOLTEN_FIST,
    CardId.OFFERING,
    CardId.ONE_TWO_PUNCH_CARD,
    CardId.PACTS_END,
    CardId.PERFECTED_STRIKE,
    CardId.PILLAGE,
    CardId.POMMEL_STRIKE,
    CardId.PRIMAL_FORCE,
    CardId.PYRE,
    CardId.RAGE_CARD,
    CardId.RAMPAGE,
    CardId.RUPTURE_CARD,
    CardId.SECOND_WIND,
    CardId.SETUP_STRIKE_CARD,
    CardId.SHRUG_IT_OFF,
    CardId.SPITE,
    CardId.STAMPEDE_CARD,
    CardId.STOKE,
    CardId.STOMP,
    CardId.STONE_ARMOR,
    CardId.STRIKE_IRONCLAD,
    CardId.SWORD_BOOMERANG,
    CardId.TANK_CARD,
    CardId.TAUNT,
    CardId.TEAR_ASUNDER,
    CardId.THRASH,
    CardId.THUNDERCLAP,
    CardId.TREMBLE,
    CardId.TRUE_GRIT,
    CardId.TWIN_STRIKE,
    CardId.UNMOVABLE,
    CardId.UNRELENTING,
    CardId.UPPERCUT,
    CardId.VICIOUS_CARD,
    CardId.WHIRLWIND,
)

NECROBINDER_CARD_POOL: tuple[CardId, ...] = (
    CardId.AFTERLIFE,
    CardId.BANSHEES_CRY,
    CardId.BLIGHT_STRIKE,
    CardId.BODYGUARD,
    CardId.BONE_SHARDS,
    CardId.BORROWED_TIME,
    CardId.BURY,
    CardId.CALCIFY_CARD,
    CardId.CALL_OF_THE_VOID,
    CardId.CAPTURE_SPIRIT,
    CardId.CLEANSE,
    CardId.COUNTDOWN_CARD,
    CardId.DANSE_MACABRE,
    CardId.DEATH_MARCH,
    CardId.DEATHBRINGER,
    CardId.DEATHS_DOOR,
    CardId.DEBILITATE_CARD,
    CardId.DEFEND_NECROBINDER,
    CardId.DEFILE,
    CardId.DEFY,
    CardId.DELAY,
    CardId.DEMESNE,
    CardId.DEVOUR_LIFE_CARD,
    CardId.DIRGE,
    CardId.DRAIN_POWER,
    CardId.DREDGE,
    CardId.EIDOLON,
    CardId.END_OF_DAYS,
    CardId.ENFEEBLING_TOUCH,
    CardId.ERADICATE,
    CardId.FEAR,
    CardId.FETCH,
    CardId.FLATTEN,
    CardId.FORBIDDEN_GRIMOIRE,
    CardId.FRIENDSHIP,
    CardId.GLIMPSE_BEYOND,
    CardId.GRAVE_WARDEN,
    CardId.GRAVEBLAST,
    CardId.HANG,
    CardId.HAUNT,
    CardId.HIGH_FIVE,
    CardId.INVOKE,
    CardId.LEGION_OF_BONE,
    CardId.LETHALITY_CARD,
    CardId.MELANCHOLY,
    CardId.MISERY,
    CardId.NECRO_MASTERY_CARD,
    CardId.NEGATIVE_PULSE,
    CardId.NEUROSURGE,
    CardId.NO_ESCAPE,
    CardId.OBLIVION,
    CardId.PAGESTORM,
    CardId.PARSE,
    CardId.POKE,
    CardId.PROTECTOR,
    CardId.PULL_AGGRO,
    CardId.PULL_FROM_BELOW,
    CardId.PUTREFY,
    CardId.RATTLE,
    CardId.REANIMATE,
    CardId.REAP,
    CardId.REAPER_FORM,
    CardId.REAVE,
    CardId.RIGHT_HAND_HAND,
    CardId.SACRIFICE,
    CardId.SCOURGE,
    CardId.SCULPTING_STRIKE,
    CardId.SEANCE,
    CardId.SENTRY_MODE,
    CardId.SEVERANCE,
    CardId.SHARED_FATE,
    CardId.SHROUD,
    CardId.SIC_EM,
    CardId.SLEIGHT_OF_FLESH,
    CardId.SNAP,
    CardId.SOUL_STORM,
    CardId.SOW,
    CardId.SPIRIT_OF_ASH,
    CardId.SPUR,
    CardId.SQUEEZE,
    CardId.STRIKE_NECROBINDER,
    CardId.THE_SCYTHE,
    CardId.TIMES_UP,
    CardId.TRANSFIGURE,
    CardId.UNDEATH,
    CardId.UNLEASH,
    CardId.VEILPIERCER,
    CardId.WISP,
)

QUEST_CARD_POOL: tuple[CardId, ...] = (
    CardId.BYRDONIS_EGG,
    CardId.LANTERN_KEY,
    CardId.SPOILS_MAP,
)

REGENT_CARD_POOL: tuple[CardId, ...] = (
    CardId.ALIGNMENT,
    CardId.ARSENAL,
    CardId.ASTRAL_PULSE,
    CardId.BEAT_INTO_SHAPE,
    CardId.BEGONE,
    CardId.BIG_BANG,
    CardId.BLACK_HOLE,
    CardId.BOMBARDMENT,
    CardId.BULWARK,
    CardId.BUNDLE_OF_JOY,
    CardId.CELESTIAL_MIGHT,
    CardId.CHARGE,
    CardId.CHILD_OF_THE_STARS,
    CardId.CLOAK_OF_STARS,
    CardId.COLLISION_COURSE,
    CardId.COMET,
    CardId.CONQUEROR,
    CardId.CONVERGENCE,
    CardId.COSMIC_INDIFFERENCE,
    CardId.CRASH_LANDING,
    CardId.CRESCENT_SPEAR,
    CardId.CRUSH_UNDER,
    CardId.DECISIONS_DECISIONS,
    CardId.DEFEND_REGENT,
    CardId.DEVASTATE,
    CardId.DYING_STAR,
    CardId.FALLING_STAR,
    CardId.FOREGONE_CONCLUSION,
    CardId.FURNACE,
    CardId.GAMMA_BLAST,
    CardId.GATHER_LIGHT,
    CardId.GENESIS,
    CardId.GLIMMER,
    CardId.GLITTERSTREAM,
    CardId.GLOW,
    CardId.GUARDS,
    CardId.GUIDING_STAR,
    CardId.HAMMER_TIME,
    CardId.HEAVENLY_DRILL,
    CardId.HEGEMONY,
    CardId.HEIRLOOM_HAMMER,
    CardId.HIDDEN_CACHE,
    CardId.I_AM_INVINCIBLE,
    CardId.KINGLY_KICK,
    CardId.KINGLY_PUNCH,
    CardId.KNOCKOUT_BLOW,
    CardId.KNOW_THY_PLACE,
    CardId.LARGESSE,
    CardId.LUNAR_BLAST,
    CardId.MAKE_IT_SO,
    CardId.MANIFEST_AUTHORITY,
    CardId.METEOR_SHOWER,
    CardId.MONARCHS_GAZE_CARD,
    CardId.MONOLOGUE_CARD,
    CardId.NEUTRON_AEGIS,
    CardId.ORBIT,
    CardId.PALE_BLUE_DOT,
    CardId.PARRY_CARD,
    CardId.PARTICLE_WALL,
    CardId.PATTER,
    CardId.PHOTON_CUT,
    CardId.PILLAR_OF_CREATION,
    CardId.PROPHESIZE,
    CardId.QUASAR,
    CardId.RADIATE,
    CardId.REFINE_BLADE,
    CardId.REFLECT_CARD,
    CardId.RESONANCE,
    CardId.ROYAL_GAMBLE,
    CardId.ROYALTIES_CARD,
    CardId.SEEKING_EDGE,
    CardId.SEVEN_STARS,
    CardId.SHINING_STRIKE,
    CardId.SOLAR_STRIKE,
    CardId.SPECTRUM_SHIFT,
    CardId.SPOILS_OF_BATTLE,
    CardId.STARDUST,
    CardId.STRIKE_REGENT,
    CardId.SUMMON_FORTH,
    CardId.SUPERMASSIVE,
    CardId.SWORD_SAGE,
    CardId.TERRAFORMING,
    CardId.THE_SEALED_THRONE,
    CardId.THE_SMITH,
    CardId.TYRANNY_CARD,
    CardId.VENERATE,
    CardId.VOID_FORM,
    CardId.WROUGHT_IN_WAR,
)

SILENT_CARD_POOL: tuple[CardId, ...] = (
    CardId.ABRASIVE,
    CardId.ACCELERANT,
    CardId.ACCURACY_CARD,
    CardId.ACROBATICS,
    CardId.ADRENALINE,
    CardId.AFTERIMAGE_CARD,
    CardId.ANTICIPATE,
    CardId.ASSASSINATE,
    CardId.BACKFLIP,
    CardId.BACKSTAB,
    CardId.BLADE_OF_INK,
    CardId.BLADE_DANCE,
    CardId.BLUR_CARD,
    CardId.BOUNCING_FLASK,
    CardId.BUBBLE_BUBBLE,
    CardId.BULLET_TIME,
    CardId.BURST,
    CardId.CALCULATED_GAMBLE,
    CardId.CLOAK_AND_DAGGER,
    CardId.CORROSIVE_WAVE,
    CardId.DAGGER_SPRAY,
    CardId.DAGGER_THROW,
    CardId.DASH,
    CardId.DEADLY_POISON,
    CardId.DEFEND_SILENT,
    CardId.DEFLECT,
    CardId.DODGE_AND_ROLL,
    CardId.ECHOING_SLASH,
    CardId.ENVENOM_CARD,
    CardId.ESCAPE_PLAN,
    CardId.EXPERTISE,
    CardId.EXPOSE,
    CardId.FAN_OF_KNIVES_CARD,
    CardId.FINISHER,
    CardId.FLANKING,
    CardId.FLECHETTES,
    CardId.FLICK_FLACK,
    CardId.FOLLOW_THROUGH,
    CardId.FOOTWORK,
    CardId.GRAND_FINALE,
    CardId.HAND_TRICK,
    CardId.HAZE,
    CardId.HIDDEN_DAGGERS,
    CardId.INFINITE_BLADES_CARD,
    CardId.KNIFE_TRAP,
    CardId.LEADING_STRIKE,
    CardId.LEG_SWEEP,
    CardId.MALAISE,
    CardId.MASTER_PLANNER,
    CardId.MEMENTO_MORI,
    CardId.MIRAGE,
    CardId.MURDER,
    CardId.NEUTRALIZE,
    CardId.NIGHTMARE,
    CardId.NOXIOUS_FUMES_CARD,
    CardId.OUTBREAK_CARD,
    CardId.PHANTOM_BLADES_CARD,
    CardId.PIERCING_WAIL,
    CardId.PINPOINT,
    CardId.POISONED_STAB,
    CardId.POUNCE,
    CardId.PRECISE_CUT,
    CardId.PREDATOR,
    CardId.PREPARED,
    CardId.REFLEX,
    CardId.RICOCHET,
    CardId.SERPENT_FORM_CARD,
    CardId.SHADOW_STEP,
    CardId.SHADOWMELD,
    CardId.SKEWER,
    CardId.SLICE,
    CardId.SNAKEBITE,
    CardId.SNEAKY_CARD,
    CardId.SPEEDSTER_CARD,
    CardId.STORM_OF_STEEL,
    CardId.STRANGLE,
    CardId.STRIKE_SILENT,
    CardId.SUCKER_PUNCH,
    CardId.SUPPRESS,
    CardId.SURVIVOR,
    CardId.TACTICIAN,
    CardId.THE_HUNT,
    CardId.TOOLS_OF_THE_TRADE,
    CardId.TRACKING,
    CardId.UNTOUCHABLE,
    CardId.UP_MY_SLEEVE,
    CardId.WELL_LAID_PLANS,
    CardId.WRAITH_FORM,
)

STATUS_CARD_POOL: tuple[CardId, ...] = (
    CardId.BECKON,
    CardId.BURN,
    CardId.DAZED,
    CardId.DEBRIS,
    CardId.FRANTIC_ESCAPE,
    CardId.INFECTION,
    CardId.SLIMED,
    CardId.SOOT,
    CardId.TOXIC,
    CardId.VOID,
    CardId.WOUND,
)

TOKEN_CARD_POOL: tuple[CardId, ...] = (
    CardId.DISINTEGRATION,
    CardId.FUEL,
    CardId.GIANT_ROCK,
    CardId.LUMINESCE,
    CardId.MIND_ROT,
    CardId.MINION_DIVE_BOMB,
    CardId.MINION_SACRIFICE,
    CardId.MINION_STRIKE,
    CardId.SHIV,
    CardId.SLOTH_STATUS,
    CardId.SOUL,
    CardId.SOVEREIGN_BLADE,
    CardId.SWEEPING_GAZE,
    CardId.WASTE_AWAY,
)

CHARACTER_CARD_POOLS_BY_ID: dict[CardPoolId, tuple[CardId, ...]] = {
    CardPoolId.IRONCLAD: IRONCLAD_CARD_POOL,
    CardPoolId.SILENT: SILENT_CARD_POOL,
    CardPoolId.DEFECT: DEFECT_CARD_POOL,
    CardPoolId.REGENT: REGENT_CARD_POOL,
    CardPoolId.NECROBINDER: NECROBINDER_CARD_POOL,
}

SHARED_CARD_POOLS_BY_ID: dict[CardPoolId, tuple[CardId, ...]] = {
    CardPoolId.COLORLESS: COLORLESS_CARD_POOL,
    CardPoolId.CURSE: CURSE_CARD_POOL,
    CardPoolId.DEPRECATED: DEPRECATED_CARD_POOL,
    CardPoolId.EVENT: EVENT_CARD_POOL,
    CardPoolId.QUEST: QUEST_CARD_POOL,
    CardPoolId.STATUS: STATUS_CARD_POOL,
    CardPoolId.TOKEN: TOKEN_CARD_POOL,
}

STATUS_MODULE_CARD_POOL: tuple[CardId, ...] = (
    CURSE_CARD_POOL
    + DEPRECATED_CARD_POOL
    + EVENT_CARD_POOL
    + QUEST_CARD_POOL
    + STATUS_CARD_POOL
    + TOKEN_CARD_POOL
)

ALL_CARD_POOL: tuple[CardId, ...] = (
    IRONCLAD_CARD_POOL
    + SILENT_CARD_POOL
    + REGENT_CARD_POOL
    + NECROBINDER_CARD_POOL
    + DEFECT_CARD_POOL
    + COLORLESS_CARD_POOL
    + STATUS_MODULE_CARD_POOL
)
